services:
  - type: worker
    name: shribots-whisper-bot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: API_ID
        value: "25136703"
      - key: API_HASH
        value: "accfaf5ecd981c67e481328515c39f89"
      - key: BOT_TOKEN
        value: "8089842083:AAFmU0Jma_HNWfo7hvazxIQEw_woliuHzDE"
      - key: ADMIN_ID
        value: "8027090675"
