services:
  - type: web
    name: shribots-whisper-bot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: API_ID
        value: "25136703"
      - key: API_HASH
        value: "accfaf5ecd981c67e481328515c39f89"
      - key: BOT_TOKEN
        value: "8446617965:AAHSQ1rp1eCWUs5XQhwcfuACnQtjsKG1STU"
      - key: ADMIN_ID
        value: "8027090675"
      - key: PORT
        value: "10000"
