services:
  - type: web
    name: shribots-whisper-bot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: API_ID
        value: "25136703"
      - key: API_HASH
        value: "accfaf5ecd981c67e481328515c39f89"
      - key: BOT_TOKEN
        value: "8528052870:AAF0cVTJxKOUG5m7ANdQrTiRGCovV3C7pRI"
      - key: ADMIN_ID
        value: "8272213732"
      - key: PORT
        value: "10000"
