services:
  - type: worker
    name: shribots-whisper-bot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: API_ID
        value: "25136703"
      - key: API_HASH
        value: "accfaf5ecd981c67e481328515c39f89"
      - key: BOT_TOKEN
        value: "8446617965:AAFWcmJw1W7xWoRRXW8UUOPBSFJBMDfQ1V4"
      - key: ADMIN_ID
        value: "8027090675"
